name:                ini-parser
version:             0.1.0.0
github:              "evturn/haskellbook"
license:             BSD3
author:              "Evan Turner"
maintainer:          "ev@evturn.com"
copyright:           "Copyright (c) 2018 Evan Turner"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Very Cool

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Configurations, am I right?

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs:       src
  build-depends:     base >=4.7 && <5
                   , bytestring 
                   , containers
                   , hspec
                   , raw-strings-qq
                   , text
                   , trifecta
  exposed-modules:   Parser

executables:
  ini-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ini-parser
